# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
      files: \.py$
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: double-quote-string-fixer
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-quotes',
        ]