# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer
      files: \.py$
    - id: mixed-line-ending
    - id: trailing-whitespace
      files: \.py$
    - id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
    - id: black
      language_version: python3
      args: [--check]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args:
        - --ignore=D202,D204
        - --max-line-length=89
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
        ]